###服务启动端口号  微信服务  wx
server:
  port: 8200
###注册到eureka的名字
spring:
  application:
    name: brhds-weixin
###注册到eureka的地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka